### ISSUE TITLE
Content in table not updating on new payload unless clicked

### ISSUE THREAD

**Issue by OpusSupo** [Gippsman2017/node-red-node-ui-etable#10] opened 2020-05-12 16:19 UTC
It seems there is a bug in the etable node that prevents it from updating upon receiving a new payload, unless you have clicked in one of the cells in between payloads.

See the attached flow for a demonstration. The bottom table is the standard non-editable table-node. I'm using the etable to make a context stored table, but it is a bit cumbersome to use because of this issue.

[etable_update_issue.txt](https://github.com/Gippsman2017/node-red-node-ui-etable/files/4616891/etable_update_issue.txt)

PS: thanks for an otherwise great node!

`[{"id":"efdde888.f57938","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"50a9024e.b060cc","type":"inject","z":"efdde888.f57938","name":"Oppstart","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":true,"onceDelay":"1","x":120,"y":80,"wires":[["8172207c.8bb8"]]},{"id":"8172207c.8bb8","type":"function","z":"efdde888.f57938","name":"Fill table default","func":"//Eksempel \"Utepils\" (fra bryggselv.no)\nmsg.payload = [\n{ \"t\" : 10,    \"h\" : 48    },\n{ \"t\" : 13,    \"h\" : 24    },\n{ \"t\" : 17,    \"h\" : 24    },\n{ \"t\" : 19,    \"h\" : 48    },\n{ \"t\" : 5,    \"h\" : 168    }];\nvar A1 = msg.payload\nflow.set(\"temptable\", A1);\nreturn msg;","outputs":1,"noerr":0,"x":360,"y":80,"wires":[["abe9a0f4.b9ea7","2e66e59.a63ba1a"]]},{"id":"abe9a0f4.b9ea7","type":"ui_etable","z":"efdde888.f57938","payload":"[{\"title\":\"Steg\",\"formatter\":\"rownum\",\"align\":\"center\",\"width\":50,\"headerSort\":false},{\"title\":\"Temp [C]\",\"field\":\"t\",\"width\":70,\"headerSort\":false,\"editor\":\"number\",\"editorParams\":{\"min\":-6,\"max\":30,\"step\":0.1}},{\"title\":\"Tid [hrs]\",\"field\":\"h\",\"width\":70,\"headerSort\":false,\"editor\":\"number\",\"editorParams\":{\"min\":0,\"step\":0.5}}]","payloadType":"json","options":"{\"movableColumns\":false,\"layout\":\"fitColumns\",\"pagination\":\"local\",\"height\":\"500px\"}","group":"9e4bf82a.e8e348","name":"Temp etable","order":2,"width":"5","height":"7","columns":[],"outputs":1,"cts":false,"x":670,"y":80,"wires":[["d22573c0.47df3"]]},{"id":"b6f92539.0e6878","type":"ui_button","z":"efdde888.f57938","name":"","group":"9e4bf82a.e8e348","order":3,"width":"5","height":"1","passthru":false,"label":"Add row","tooltip":"Trykk for å legge til et steg i temperaturprogrammet","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":260,"y":160,"wires":[["930767c3.752588"]]},{"id":"bf5eef44.dd696","type":"ui_button","z":"efdde888.f57938","name":"","group":"9e4bf82a.e8e348","order":4,"width":"5","height":"1","passthru":false,"label":"Delete row","tooltip":"Trykk for å fjerne siste rad i temperaturprogrammet","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":270,"y":200,"wires":[["cddda789.26f468"]]},{"id":"cddda789.26f468","type":"function","z":"efdde888.f57938","name":"Remove Row","func":"var A1 = flow.get(\"temptable\");\nA1.pop();\nmsg.payload = A1;\nflow.set(\"temptable\", A1);\nreturn msg;","outputs":1,"noerr":0,"x":460,"y":200,"wires":[["abe9a0f4.b9ea7","2e66e59.a63ba1a"]]},{"id":"930767c3.752588","type":"function","z":"efdde888.f57938","name":"Add Row","func":"var A1 = flow.get(\"temptable\");\nA1.push({ \"t\" : 0,    \"h\" : 0    });\nmsg.payload = A1;\nflow.set(\"temptable\", A1);\nreturn msg;","outputs":1,"noerr":0,"x":440,"y":160,"wires":[["abe9a0f4.b9ea7","2e66e59.a63ba1a"]]},{"id":"2e66e59.a63ba1a","type":"ui_table","z":"efdde888.f57938","group":"9e4bf82a.e8e348","name":"Temp table","order":6,"width":"5","height":"7","columns":[{"field":"","title":"Steg","width":"50","align":"center","formatter":"rownum","formatterParams":{"target":"_blank"}},{"field":"t","title":"Temp [C]","width":"70","align":"left","formatter":"plaintext","formatterParams":{"target":"_blank"}},{"field":"h","title":"Tid [hrs]","width":"70","align":"left","formatter":"plaintext","formatterParams":{"target":"_blank"}}],"outputs":1,"cts":true,"x":810,"y":180,"wires":[[]]},{"id":"d22573c0.47df3","type":"function","z":"efdde888.f57938","name":"flow temp table","func":"var A1 = msg.options.data;\nflow.set(\"temptable\", A1);\nmsg.payload = A1;\nmsg.topic = \"temptable\";\nreturn msg;","outputs":1,"noerr":0,"x":880,"y":80,"wires":[[]]},{"id":"f53460eb.0c533","type":"ui_text","z":"efdde888.f57938","group":"9e4bf82a.e8e348","order":1,"width":0,"height":0,"name":"","label":"etable:","format":"{{msg.payload}}","layout":"row-spread","x":650,"y":40,"wires":[]},{"id":"36c39882.c3fb28","type":"ui_text","z":"efdde888.f57938","group":"9e4bf82a.e8e348","order":5,"width":0,"height":0,"name":"","label":"normal table:","format":"{{msg.payload}}","layout":"row-spread","x":810,"y":140,"wires":[]},{"id":"9e4bf82a.e8e348","type":"ui_group","z":"","name":"Test","tab":"c5896101.825f7","order":1,"disp":true,"width":"5","collapse":false},{"id":"c5896101.825f7","type":"ui_tab","z":"","name":"Etable test","icon":"dashboard","disabled":false,"hidden":false}]`

**Comment by OpusSupo** [comment] 2020-05-12 18:51
I'm able to force it to update it by cycling msg.enabled towards the etable node and refilling it. OK workaround for now.

**Comment by Gippsman2017** [comment] 2020-05-13 00:51
Thanks for the great heads up.
Fault was caused by missing emitOnlyNewValues: false in widget startup, fixed in V1.0.2

**Closed as completed by Gippsman2017** 2020-05-13 00:51 UTC
